/* Fourteen Nights: self-contained Canvas survival game. */
const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const overlay = document.querySelector('#overlay');
const hud = document.querySelector('#hud');
const ui = {
  night: document.querySelector('#nightLabel'), timer: document.querySelector('#timerLabel'), cash: document.querySelector('#cashLabel'),
  barricadeBar: document.querySelector('#barricadeBar'), barricadeText: document.querySelector('#barricadeText'),
  healthBar: document.querySelector('#healthBar'), healthText: document.querySelector('#healthText'), weapon: document.querySelector('#weaponHud'), status: document.querySelector('#topStatus')
};

const W = 1280, H = 720;
const ACTOR_SCALE = 1.25, PLAYER_HIT_RADIUS = 26;
const keys = new Set();
const mouse = { x: 400, y: 360, down: false };
const weapons = {
  pistol: { name:'PISTOL', price:0, mag:12, reload:1.2, damage:20, fire:.29, bulletSpeed:1080, color:'#edf3f5' },
  revolver: { name:'REVOLVER', price:300, mag:6, reload:1.8, damage:90, fire:.48, bulletSpeed:1160, pierce:1, color:'#ffcf54' },
  shotgun: { name:'PUMP SHOTGUN', price:650, mag:6, reload:2.4, damage:28, fire:.72, bulletSpeed:900, pellets:8, spread:.22, color:'#ffcf54' },
  smg: { name:'SMG', price:950, mag:30, reload:2, damage:24, fire:.085, bulletSpeed:1060, color:'#c8ff58' },
  rifle: { name:'HUNTING RIFLE', price:1350, mag:5, reload:2.2, damage:150, fire:.65, bulletSpeed:1450, pierce:3, color:'#a6dcff' },
  ar: { name:'ASSAULT RIFLE', price:1800, mag:24, reload:2.1, damage:58, fire:.16, bulletSpeed:1190, color:'#ffcf54' },
  lmg: { name:'LIGHT MACHINE GUN', price:2600, mag:60, reload:4, damage:42, fire:.1, bulletSpeed:1150, color:'#ff934b' },
  moonbeam: { name:'MOONBEAM-9', price:4500, mag:8, reload:2.8, damage:180, fire:.46, bulletSpeed:1150, pierce:8, color:'#ff4bdf', rare:true }
};
const types = {
  shambler: { hp:100, speed:42, barr:4, cash:20, r:20, color:'#8cab6a', weight:55 },
  runner: { hp:75, speed:92, barr:3, cash:25, r:17, color:'#d3e076', weight:22 },
  tough: { hp:220, speed:30, barr:12, cash:45, r:27, color:'#596873', weight:12, armor:true },
  spitter: { hp:120, speed:38, barr:2, cash:35, r:21, color:'#93c987', weight:8, spit:true },
  clown: { hp:90, speed:58, barr:5, cash:60, r:20, color:'#fd855f', weight:3, clown:true }
};
const survivorPool = [
  ['Mechanic Mae', 'Repairs restore +20 barricade health.', 'mechanic'], ['Nurse Nia', 'Restores 20 player health at dawn.', 'nurse'],
  ['Officer Ortiz', 'Your first reload each night is instant.', 'officer'], ['Accountant Al', '+12% cash from kills.', 'accountant'],
  ['Inventor Izzy', 'Better odds of Moonbeam-9 parts.', 'inventor'], ['Cook Carl', '+15% movement speed for the first 5 seconds.', 'cook']
];
let state, last = 0, audio = false, audioCtx;
function tone(freq, duration=.06, type='square', volume=.025) { if(!audio)return; audioCtx ||= new (window.AudioContext||window.webkitAudioContext)(); const osc=audioCtx.createOscillator(), gain=audioCtx.createGain(); osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration); }
function defaultState() { return { scene:'title', night:1, cash:0, scrap: +(localStorage.getItem('fn_scrap') || 0), upgrades: JSON.parse(localStorage.getItem('fn_upgrades') || '{}'), player:{x:270,y:445,hp:100}, barricade:100, maxBarr:100, armory:['pistol'], weapons:['pistol',null], survivorLoadout:{}, selected:0, ammo:{pistol:12}, reload:0, fireCd:0, instantReload:true, zombies:[], bullets:[], particles:[], acid:[], survivors:[], bots:[], elapsed:0, spawnClock:1, killed:0, shake:0, bossSpawned:false, bossKilled:false, betweenAction:false, nightIntro:0 }; }

function saveProgress() { localStorage.setItem('fn_scrap', state.scrap); localStorage.setItem('fn_upgrades', JSON.stringify(state.upgrades)); }
function resetRun() { const savedScrap = +(localStorage.getItem('fn_scrap') || 0), upgrades = JSON.parse(localStorage.getItem('fn_upgrades') || '{}'); state = defaultState(); state.scrap=savedScrap; state.upgrades=upgrades; applyUpgrades(); startNight(); }
function applyUpgrades() { const u=state.upgrades; state.maxBarr += (u.barr||0)*15; state.barricade=state.maxBarr; }
function weaponId() { return state.weapons[state.selected] || state.weapons[0]; }
function weapon() { return weapons[weaponId()]; }
function weaponAmmo() { const id=weaponId(); return state.ammo[id] ?? weapons[id].mag; }
function setAmmo(v) { state.ammo[weaponId()]=v; }

const upgrades = {
  barr:{name:'REINFORCED BARRICADE',max:5,cost:75,copy:'+15 maximum barricade health'},
  hands:{name:'FAST HANDS',max:5,cost:90,copy:'-6% reload duration'},
  legs:{name:"RUNNER'S LEGS",max:4,cost:100,copy:'+5% movement speed'},
  clean:{name:'CLEAN SHOT',max:5,cost:110,copy:'+5% headshot cash'},
  scavenger:{name:'SCAVENGER',max:4,cost:120,copy:'+5% search success'},
  bargain:{name:'BARGAIN HUNTER',max:3,cost:150,copy:'-5% shop prices'}
};
function titleScreen() {
  state = defaultState(); ui.status.textContent='THE ROAD TO RESCUE'; hud.classList.add('hidden');
  overlay.innerHTML = `<div class="overlay-panel"><div class="overline">A DARKLY COMIC SURVIVAL SHOOTER</div><h1>FOURTEEN<br>NIGHTS</h1><p>Hold the barricade. Make every headshot count. Rescue arrives in fourteen dawns—assuming you do.</p><button class="action" id="start">START A NEW RUN</button><button class="action secondary" id="upgrades">SPEND SCRAP</button><div class="stat-line">${state.scrap} SCRAP BANKED &nbsp; / &nbsp; PERMANENT UPGRADES ACTIVE</div></div>`;
  document.querySelector('#start').onclick=resetRun;
  document.querySelector('#upgrades').onclick=upgradeScreen;
}
function upgradeScreen() { const cards=Object.entries(upgrades).map(([id,u])=>{const rank=state.upgrades[id]||0;const locked=rank>=u.max||state.scrap<u.cost;return `<button class="shop-item" data-upgrade="${id}" ${locked?'disabled':''}><strong>${u.name}</strong><small>RANK ${rank}/${u.max} · ${u.cost} SCRAP<br>${u.copy}</small></button>`;}).join('');showOverlay(`<div class="overline">SURVIVAL CACHE</div><h2>MAKE THE NEXT RUN COUNT.</h2><p><b style="color:#ffcf54">${state.scrap} SCRAP</b> available. Upgrades persist between runs.</p><div class="shop-grid">${cards}</div><button class="action" id="back">BACK TO THE ROAD</button>`);document.querySelectorAll('[data-upgrade]').forEach(btn=>btn.onclick=()=>buyUpgrade(btn.dataset.upgrade));document.querySelector('#back').onclick=titleScreen; }
function buyUpgrade(id) { const u=upgrades[id], rank=state.upgrades[id]||0;if(rank>=u.max||state.scrap<u.cost)return;state.scrap-=u.cost;state.upgrades[id]=rank+1;saveProgress();upgradeScreen(); }
function showOverlay(html) { overlay.innerHTML=`<div class="overlay-panel">${html}</div>`; }
function pauseGame() { if(state?.scene!=='playing')return; state.scene='paused'; mouse.down=false; showOverlay(`<div class="overline">NIGHT ${String(state.night).padStart(2,'0')} ON HOLD</div><h1>PAUSED</h1><p>The barricade and the horde are frozen. Take a breath.</p><button class="action" id="resumeGame">RESUME <small>ESC</small></button>`); document.querySelector('#resumeGame').onclick=resumeGame; }
function resumeGame() { if(state?.scene!=='paused')return; state.scene='playing'; overlay.innerHTML=''; }
function startNight() { state.scene='playing'; state.elapsed=0; state.spawnClock=.7; state.zombies=[]; state.bullets=[]; state.acid=[]; state.player.x=270; state.player.y=445; state.player.hp=Math.min(100,state.player.hp + (hasSurvivor('nurse')?20:0)); state.bots=state.survivors.map((survivor,index)=>{const weaponId=survivorWeapon(survivor);return {survivor,index,weaponId,x:365+(index%2)*84,y:220+Math.floor(index/2)*155,shotCd:.35+index*.08,accuracy:.40+Math.random()*.20,ammo:weapons[weaponId].mag,reload:0};}); state.instantReload=hasSurvivor('officer'); state.nightIntro=2.5; state.bossSpawned=false; state.bossKilled=false; overlay.innerHTML=''; hud.classList.remove('hidden'); ui.status.textContent=`HOLD UNTIL DAWN — NIGHT ${String(state.night).padStart(2,'0')}`; }
function hasSurvivor(id) { return state.survivors.some(s=>s[2]===id); }
function survivorWeapon(survivor) { return state.survivorLoadout[survivor[2]] || 'pistol'; }
function isAssignedToSurvivor(id, exceptId='') { return id!=='pistol' && Object.entries(state.survivorLoadout).some(([survivorId,weaponId])=>survivorId!==exceptId&&weaponId===id); }
function endNight() { state.scene='between'; state.scrap += 35 + (Math.floor((state.night-1)/3)*10); saveProgress(); hud.classList.add('hidden'); dawnScreen(); }
function dawnScreen() { const survivorNames=state.survivors.map(s=>s[0]).join(' · ') || 'NONE'; showOverlay(`<div class="overline">DAWN ${String(state.night).padStart(2,'0')} — 12 HOURS BEFORE DARK</div><h2>PATCH THE LINE.<br>SEARCH THE BLOCK.</h2><p>Allocate all 12 hours. Every repair hour restores <b style="color:#ff4b4b">10 barricade health</b>; search time raises the chance of finding one defender. Survivors: ${state.survivors.length}/6 (${survivorNames})</p><div class="time-allocation"><div><span>REPAIR <b id="repairHoursValue">6</b> HRS</span><input id="repairHours" type="range" min="0" max="12" value="6" /></div><div class="allocation-readout"><strong id="repairPreview">+60</strong><small>BARRICADE HEALTH</small><strong id="searchPreview">36%</strong><small>FIND CHANCE · 6 HRS</small></div></div><button class="action" id="commitDawn">CONFIRM DAWN PLAN</button>`); const slider=document.querySelector('#repairHours'); const refresh=()=>{const repair=+slider.value, search=12-repair, health=Math.round(repair*10*(hasSurvivor('mechanic')?1.25:1)), chance=Math.min(90,search*6+(hasSurvivor('inventor')?12:0)+(state.upgrades.scavenger||0)*5); document.querySelector('#repairHoursValue').textContent=repair;document.querySelector('#repairPreview').textContent=`+${health}`;document.querySelector('#searchPreview').textContent=`${chance}%`;}; slider.oninput=refresh; document.querySelector('#commitDawn').onclick=()=>resolveDawn(+slider.value); }
function resolveDawn(repairHours) { const searchHours=12-repairHours, repairAmount=Math.round(repairHours*10*(hasSurvivor('mechanic')?1.25:1)); state.barricade=Math.min(state.maxBarr,state.barricade+repairAmount); const chance=Math.min(.90,searchHours*.06+(hasSurvivor('inventor') ? .12 : 0)+(state.upgrades.scavenger||0)*.05); let result='No one answered the calls.'; if(searchHours>0&&state.survivors.length<6&&Math.random()<chance){const choices=survivorPool.filter(s=>!hasSurvivor(s[2]));const found=choices[Math.floor(Math.random()*choices.length)]||survivorPool[Math.floor(Math.random()*survivorPool.length)];state.survivors.push(found);result=`<b style="color:#c8ff58">${found[0]}</b> made it back to the barricade. They will cover you with roughly ${70+Math.floor(Math.random()*11)}% accuracy.`;}else if(state.survivors.length>=6){result='Your six-person team is full. No more room at the line.';} state.night++; showOverlay(`<div class="overline">DAWN RESULT</div><h2>${result}</h2><p>${repairHours} repair hours restored <b style="color:#ff4b4b">${repairAmount} health</b>. ${searchHours} hours were spent searching.</p><button class="action" id="toShop">OPEN ARMORY</button>`); document.querySelector('#toShop').onclick=shopScreen; }
function priceFor(w) { return Math.floor(w.price*(1-(state.upgrades.bargain||0)*.05)); }
function shopScreen() { const current=state.weapons.filter(Boolean).map(id=>weapons[id].name).join(' / '); const cards=Object.entries(weapons).map(([id,w])=>{ const price=priceFor(w), owned=state.armory.includes(id), cannot=state.cash<price||owned; return `<button class="shop-item ${owned?'owned':''}" data-weapon="${id}" ${cannot?'disabled':''}><strong>${w.name}</strong><small>${owned?'OWNED':`$${price}`} · ${w.mag} RDS · ${w.damage} DMG</small></button>`; }).join(''); showOverlay(`<div class="overline">NIGHT ${String(state.night).padStart(2,'0')} ARMORY</div><h2>BUY ONCE. EQUIP ANYTIME.</h2><p><b style="color:#c8ff58">$${state.cash}</b> available &nbsp; | &nbsp; equipped: ${current || 'PISTOL'}</p><div class="shop-grid">${cards}</div><button class="action secondary" id="loadout">PLAYER LOADOUT</button><button class="action secondary" id="survivorLoadout">SURVIVOR WEAPONS</button><button class="action" id="continue">BEGIN NIGHT ${String(state.night).padStart(2,'0')}</button>`); document.querySelectorAll('[data-weapon]').forEach(btn=>btn.onclick=()=>buy(btn.dataset.weapon)); document.querySelector('#loadout').onclick=equipScreen; document.querySelector('#survivorLoadout').onclick=survivorLoadoutScreen; document.querySelector('#continue').onclick=startNight; }
function buy(id) { const w=weapons[id], price=priceFor(w); if(state.cash<price||state.armory.includes(id))return; state.cash-=price; state.armory.push(id); state.ammo[id]=w.mag; equipScreen(); }
function equipScreen() { const entries=state.armory.map(id=>{const w=weapons[id],primary=state.weapons[0]===id,secondary=state.weapons[1]===id,loaned=isAssignedToSurvivor(id);return `<div class="armory-item"><strong>${w.name}</strong><small>${loaned?'ASSIGNED TO SURVIVOR':`${w.mag} RDS · ${w.damage} DMG`}</small><div><button data-equip="${id}" data-slot="0" ${primary||loaned?'disabled':''}>${primary?'PRIMARY':'SET PRIMARY'}</button><button data-equip="${id}" data-slot="1" ${secondary||primary||loaned?'disabled':''}>${secondary?'SECONDARY':'SET SECONDARY'}</button></div></div>`;}).join('');showOverlay(`<div class="overline">PERSISTENT ARMORY — ${state.armory.length} OWNED</div><h2>SET YOUR TWO-GUN LOADOUT.</h2><p>Primary: <b style="color:#ffcf54">${weapons[state.weapons[0]].name}</b> &nbsp;|&nbsp; Secondary: <b style="color:#ffcf54">${state.weapons[1]?weapons[state.weapons[1]].name:'EMPTY'}</b></p><div class="armory-grid">${entries}</div><button class="action secondary" id="backShop">BACK TO SHOP</button><button class="action" id="beginFromLoadout">BEGIN NIGHT ${String(state.night).padStart(2,'0')}</button>`);document.querySelectorAll('[data-equip]').forEach(btn=>btn.onclick=()=>equip(btn.dataset.equip,+btn.dataset.slot));document.querySelector('#backShop').onclick=shopScreen;document.querySelector('#beginFromLoadout').onclick=startNight;}
function equip(id,slot) { const other=slot===0?1:0;if(state.weapons[other]===id)state.weapons[other]=null;state.weapons[slot]=id;state.selected=slot;equipScreen(); }
function survivorLoadoutScreen() { const rows=state.survivors.map(survivor=>{const current=survivorWeapon(survivor),options=['pistol',...state.armory.filter(id=>id!=='pistol')].filter(id=>id===current||(!state.weapons.includes(id)&&!isAssignedToSurvivor(id,survivor[2]))).map(id=>`<option value="${id}" ${id===current?'selected':''}>${weapons[id].name}</option>`).join('');return `<label class="survivor-loadout"><span><strong>${survivor[0]}</strong><small>DEFAULT: PISTOL · 40–60% ACCURACY</small></span><select data-survivor-weapon="${survivor[2]}">${options}</select></label>`;}).join('')||'<p>No survivors yet. Allocate dawn hours to searching.</p>';showOverlay(`<div class="overline">SURVIVOR WEAPONS</div><h2>ASSIGN THE SPARE GUNS.</h2><p>Survivors automatically reload. A custom weapon can only be held by one person, while Pistols remain standard issue.</p><div class="survivor-loadout-list">${rows}</div><button class="action secondary" id="backToArmory">BACK TO ARMORY</button><button class="action" id="beginWithTeam">BEGIN NIGHT ${String(state.night).padStart(2,'0')}</button>`);document.querySelectorAll('[data-survivor-weapon]').forEach(select=>select.onchange=()=>assignSurvivorWeapon(select.dataset.survivorWeapon,select.value));document.querySelector('#backToArmory').onclick=shopScreen;document.querySelector('#beginWithTeam').onclick=startNight;}
function assignSurvivorWeapon(survivorId, weaponId) { state.survivorLoadout[survivorId]=weaponId;if(weaponId!=='pistol'){state.weapons=state.weapons.map(id=>id===weaponId?null:id);if(!state.weapons[0]){state.weapons[0]='pistol';state.selected=0;}}survivorLoadoutScreen(); }

function spawnZombie(typeName, boss=false) { const t=types[typeName] || types.shambler; const y=165+Math.random()*440; state.zombies.push({ ...t, r:t.r*ACTOR_SCALE, type:typeName, x:1325+Math.random()*60,y, maxHp:t.hp,hp:t.hp, boss, headHp:boss?3:(t.armor?2:1), attackCd:0, bob:Math.random()*6.28 }); }
function spawnBoss() { const t=state.night===7 ? {hp:1800,speed:28,barr:45,cash:400,r:53*ACTOR_SCALE,color:'#8e6a58',type:'foreman',boss:true,headHp:6,maxHp:1800} : {hp:3600,speed:34,barr:38,cash:400,r:62*ACTOR_SCALE,color:'#aa687b',type:'passenger',boss:true,headHp:8,maxHp:3600}; state.zombies.push({...t,x:1340,y:410,attackCd:0,bob:0}); state.bossSpawned=true; }
function chooseType() { const n=state.night; let pool=['shambler']; if(n>=2) pool.push('runner'); if(n>=4)pool.push('tough'); if(n>=3)pool.push('spitter'); if(n>=8)pool.push('clown'); const weighted=pool.flatMap(k=>Array(Math.max(1,Math.round(types[k].weight/(k==='tough'&&n<6?2:1)))).fill(k)); return weighted[Math.floor(Math.random()*weighted.length)]; }
function shoot() { const w=weapon(); if(state.reload>0||state.fireCd>0||weaponAmmo()<=0)return; setAmmo(weaponAmmo()-1); tone(w.name==='PUMP SHOTGUN'?72:w.name==='MOONBEAM-9'?410:125,.07,w.name==='MOONBEAM-9'?'sine':'square',.035); state.fireCd=w.fire; state.shake=Math.max(state.shake,w.name==='PUMP SHOTGUN'?7:2); const angle=Math.atan2(mouse.y-state.player.y,mouse.x-state.player.x); const count=w.pellets||1; for(let i=0;i<count;i++){const a=angle+(Math.random()-.5)*(w.spread||.025); state.bullets.push({x:state.player.x+35*Math.cos(a),y:state.player.y+35*Math.sin(a),vx:Math.cos(a)*w.bulletSpeed,vy:Math.sin(a)*w.bulletSpeed,damage:w.damage,pierce:w.pierce||0,color:w.color,life:1.1,moon:w.name==='MOONBEAM-9',trail:76});} burst(state.player.x+30*Math.cos(angle),state.player.y+30*Math.sin(angle),w.color,9,130); if(weaponAmmo()===0) reload(); }
function reload() { if(state.reload>0||weaponAmmo()>=weapon().mag)return; tone(280,.05,'square',.018); state.reload=state.instantReload?0.05:weapon().reload*(1-(state.upgrades.hands||0)*.06); state.instantReload=false; }
function killZombie(z, headshot=false) { const index=state.zombies.indexOf(z); if(index<0)return; state.zombies.splice(index,1); tone(headshot?220:150,.06,'sawtooth',.018); const bonus=(hasSurvivor('accountant')?1.12:1)*(headshot?1+(state.upgrades.clean||0)*.05:1); state.cash+=Math.ceil(z.cash*bonus); state.killed++; burst(z.x,z.y,z.color,18,190); if(z.boss){ state.bossKilled=true; for(let i=0;i<28;i++)burst(z.x+(Math.random()-.5)*90,z.y+(Math.random()-.5)*90,'#ff4b4b',3,260); } }
function burst(x,y,color,count,speed) { for(let i=0;i<count;i++){const a=Math.random()*6.28,s=speed*(.25+Math.random()*.75); state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:.25+Math.random()*.45,r:1+Math.random()*3});} }

function update(dt) { if(state.scene!=='playing')return; state.elapsed+=dt; state.fireCd=Math.max(0,state.fireCd-dt); if(state.reload>0){ state.reload-=dt; if(state.reload<=0)setAmmo(weapon().mag); } if(weaponAmmo()===0&&state.reload<=0)reload(); if(mouse.down) shoot(); if(keys.has('r')){ reload(); keys.delete('r'); } if(keys.has('1')){state.selected=0;keys.delete('1');} if(keys.has('2')&&state.weapons[1]){state.selected=1;keys.delete('2');}
  const speed=230*(1+(state.upgrades.legs||0)*.05)*(hasSurvivor('cook')&&state.elapsed<5?1.15:1); let dx=(keys.has('d')?1:0)-(keys.has('a')?1:0),dy=(keys.has('s')?1:0)-(keys.has('w')?1:0); if(dx||dy){const l=Math.hypot(dx,dy); state.player.x+=dx/l*speed*dt;state.player.y+=dy/l*speed*dt;} state.player.x=Math.max(55,Math.min(535,state.player.x));state.player.y=Math.max(158,Math.min(647,state.player.y));
  for(const bot of state.bots){const botWeapon=weapons[bot.weaponId];if(bot.reload>0){bot.reload-=dt;if(bot.reload<=0)bot.ammo=botWeapon.mag;continue;}if(bot.ammo===0){bot.reload=botWeapon.reload;continue;}bot.shotCd-=dt;if(bot.shotCd>0||!state.zombies.length)continue;bot.shotCd=botWeapon.fire*1.9+.22+Math.random()*.16;const target=state.zombies.reduce((best,z)=>!best||z.x<best.x?z:best,null),hits=Math.random()<bot.accuracy,aimX=target.x,aimY=target.y+(hits?8:(Math.random()-.5)*150),a=Math.atan2(aimY-bot.y,aimX-bot.x);bot.ammo--;state.bullets.push({x:bot.x+32*Math.cos(a),y:bot.y+32*Math.sin(a),vx:Math.cos(a)*botWeapon.bulletSpeed*.86,vy:Math.sin(a)*botWeapon.bulletSpeed*.86,damage:botWeapon.damage,pierce:botWeapon.pierce||0,color:'#c8ff58',life:1.15,moon:false,trail:56,bot:true});burst(bot.x+28*Math.cos(a),bot.y+28*Math.sin(a),'#c8ff58',4,80);if(bot.ammo===0)bot.reload=botWeapon.reload;}
  const timeLeft=90-state.elapsed; const bossNight=state.night===7||state.night===14; if(bossNight&&!state.bossSpawned&&state.elapsed>=(state.night===14?35:45)) spawnBoss(); state.spawnClock-=dt; if(state.spawnClock<=0){const batch=Math.min(5,1+Math.floor((state.night-1)/3));for(let i=0;i<batch;i++)spawnZombie(chooseType());const start=Math.max(.32,2.75-state.night*.17), end=Math.max(.20,1.45-state.night*.085), p=Math.min(1,state.elapsed/90); state.spawnClock=(start+(end-start)*p)*(state.bossSpawned?1.25:1); }
  for(const b of [...state.bullets]){ b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt; let remove=b.life<=0||b.x<0||b.x>W||b.y<0||b.y>H; for(const z of [...state.zombies]){if(remove)break; const d=Math.hypot(b.x-z.x,b.y-z.y), head=Math.hypot(b.x-z.x,b.y-(z.y-z.r*.68)); if(head<z.r*.62){ z.headHp--; burst(b.x,b.y,'#fff',8,125); if(z.headHp<=0)killZombie(z,true); remove=true; } else if(d<z.r){ z.hp-=b.damage*(z.armor?.75:1); burst(b.x,b.y,'#d8ffbd',5,95); if(z.hp<=0)killZombie(z,false); if(b.pierce>0)b.pierce--;else remove=true; }} if(remove)state.bullets.splice(state.bullets.indexOf(b),1); }
  for(const z of [...state.zombies]) { const stopped = z.spit && z.x<760 && state.barricade>0; const targetX=state.barricade>0?610:state.player.x; const targetY=state.barricade>0?z.y:state.player.y; const dist=Math.hypot(targetX-z.x,targetY-z.y); if(stopped){z.attackCd-=dt;if(z.attackCd<=0){state.acid.push({x:z.x,y:z.y,vx:-260,vy:(state.player.y-z.y)*.38,life:3});z.attackCd=4;}} else if(dist>z.r+PLAYER_HIT_RADIUS){z.x+=(targetX-z.x)/dist*z.speed*dt;z.y+=(targetY-z.y)/dist*z.speed*dt;} else if(state.barricade>0){ state.barricade=Math.max(0,state.barricade-z.barr*dt*.45); } else { gameOver(); return; } if(z.boss){const ratio=z.hp/z.maxHp; const crossed=Math.floor((1-ratio)*4); if((z.spawned||0)<crossed){z.spawned=crossed; for(let i=0;i<(z.type==='passenger'?4:6);i++)spawnZombie(z.type==='passenger'?'runner':'shambler');}} }
  for(const a of [...state.acid]){a.x+=a.vx*dt;a.y+=a.vy*dt;a.life-=dt;if(Math.hypot(a.x-state.player.x,a.y-state.player.y)<PLAYER_HIT_RADIUS){state.player.hp-=18;state.acid.splice(state.acid.indexOf(a),1);burst(a.x,a.y,'#c8ff58',10,80);if(state.player.hp<=0){gameOver();return;}}else if(a.life<=0)state.acid.splice(state.acid.indexOf(a),1);}
  for(const p of [...state.particles]){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.92;p.vy*=.92;p.life-=dt;if(p.life<=0)state.particles.splice(state.particles.indexOf(p),1);} state.shake=Math.max(0,state.shake-dt*20); if((!bossNight&&timeLeft<=0)||(bossNight&&state.bossKilled&&timeLeft<=0)){if(state.night===14)victory();else endNight();} updateHud(timeLeft); }
function updateHud(left) { ui.night.textContent=String(state.night).padStart(2,'0');ui.timer.textContent=`${String(Math.max(0,Math.ceil(left)/60|0)).padStart(2,'0')}:${String(Math.max(0,Math.ceil(left)%60)).padStart(2,'0')}`; ui.cash.textContent='$'+state.cash;ui.barricadeBar.style.width=(100*state.barricade/state.maxBarr)+'%';ui.barricadeText.textContent=`${Math.ceil(state.barricade)} / ${state.maxBarr}`;ui.healthBar.style.width=state.player.hp+'%';ui.healthText.textContent=`${Math.ceil(state.player.hp)} / 100`;const w=weapon();ui.weapon.innerHTML=`<span class="weapon-name">${w.name}</span><span class="ammo">${weaponAmmo()} / ${w.mag}</span>${state.reload>0?'<span class="reload">RELOADING</span>':''}`; }

function gameOver(){ if(state.scene!=='playing')return;state.scene='gameover';state.scrap+=Math.max(0,(state.night-1)*15);saveProgress();hud.classList.add('hidden');showOverlay(`<div class="overline">THE BITE WAS FATAL</div><h1>YOU MADE IT<br>TO NIGHT ${String(state.night).padStart(2,'0')}</h1><p>The rescue keeps circling. Your permanent Scrap has been banked—make the next stand stronger.</p><div class="stat-line">${state.scrap} TOTAL SCRAP</div><button class="action" id="again">TRY AGAIN</button>`);document.querySelector('#again').onclick=resetRun; }
function victory(){state.scene='victory';state.scrap+=300;saveProgress();hud.classList.add('hidden');showOverlay(`<div class="overline">NIGHT 14 COMPLETE</div><h1>RESCUE<br>ARRIVED.</h1><p>You put down the Passenger, climbed the rope ladder, and left the neighborhood to its bad decisions.</p><div class="stat-line">+300 SCRAP &nbsp; / &nbsp; ${state.killed} ZOMBIES PUT TO REST</div><button class="action" id="again">SURVIVE AGAIN</button>`);document.querySelector('#again').onclick=resetRun;}

function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(state?.shake){ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake)} const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#101b31');g.addColorStop(.56,'#0e1726');g.addColorStop(.561,'#11181e');g.addColorStop(1,'#070b10');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  // ruined city
  ctx.fillStyle='#080e19';[[0,120,110,260],[115,70,95,310],[220,160,145,220],[870,90,120,290],[1002,140,150,240],[1160,55,120,325]].forEach(([x,y,w,h])=>ctx.fillRect(x,y,w,h));ctx.fillStyle='rgba(209,231,170,.08)';for(let x=20;x<W;x+=58)for(let y=105;y<310;y+=54)ctx.fillRect(x,y,8,16);
  // rain and ground
  ctx.strokeStyle='rgba(195,224,255,.16)';ctx.lineWidth=1;for(let i=0;i<88;i++){const x=(i*79+(performance.now()/15)%79)%W,y=(i*43+(performance.now()/7)%570);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+20);ctx.stroke();}ctx.fillStyle='#090e13';ctx.fillRect(0,512,W,208);ctx.strokeStyle='rgba(160,196,215,.16)';ctx.beginPath();ctx.moveTo(0,620);ctx.lineTo(W,602);ctx.stroke();
  // Fortified choke point: concrete walls show the protected lane; timber fills the entire opening.
  ctx.fillStyle='#202a32';ctx.fillRect(410,112,185,32);ctx.fillRect(410,648,185,32);ctx.fillStyle='#34424a';ctx.fillRect(430,122,165,8);ctx.fillRect(430,654,165,8);ctx.fillStyle='#12181d';ctx.fillRect(548,112,48,568);ctx.fillStyle='rgba(200,220,230,.13)';for(let x=422;x<585;x+=36){ctx.fillRect(x,116,5,20);ctx.fillRect(x,650,5,20);}
  const broken=state&&state.barricade<=0; if(!broken){ctx.fillStyle='#4e3327';ctx.fillRect(574,136,38,512);ctx.fillStyle='#76503a';for(let y=151;y<635;y+=62){ctx.fillRect(530,y,95,20);ctx.fillStyle='#8a6045';ctx.fillRect(536,y+3,76,5);ctx.fillStyle='#76503a';}ctx.fillStyle='#a2b3b5';ctx.fillRect(571,132,7,520);ctx.fillRect(610,132,7,520);ctx.strokeStyle='#251610';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(534,143);ctx.lineTo(618,638);ctx.moveTo(618,143);ctx.lineTo(534,638);ctx.stroke();ctx.fillStyle='#d7dfd1';ctx.font='600 11px DM Mono';ctx.fillText('BARRICADE',526,103);}else{ctx.fillStyle='#563b2c';for(let i=0;i<10;i++)ctx.fillRect(545+(i%3)*26,145+i*48,42,11);}
  if(!state){ctx.restore();return;} // entities
  for(const a of state.acid){ctx.fillStyle='#c8ff58';ctx.beginPath();ctx.arc(a.x,a.y,6,0,7);ctx.fill();}
  for(const b of state.bullets){ctx.save();ctx.globalAlpha=Math.min(1,b.life*4);ctx.strokeStyle=b.color;ctx.shadowColor=b.color;ctx.shadowBlur=b.moon?18:10;ctx.lineWidth=b.moon?8:4;ctx.beginPath();const l=b.trail/Math.hypot(b.vx,b.vy);ctx.moveTo(b.x-b.vx*l,b.y-b.vy*l);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,b.moon?4:2.4,0,7);ctx.fill();ctx.restore();}
  for(const z of state.zombies){drawZombie(z);}
  for(const bot of state.bots)drawBot(bot); drawPlayer();for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();}ctx.globalAlpha=1;
  if(state.nightIntro>0&&state.scene==='playing'){state.nightIntro-=1/60;ctx.fillStyle='rgba(4,8,16,.55)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#edf3f5';ctx.font='800 68px Barlow Condensed';ctx.fillText(`NIGHT ${String(state.night).padStart(2,'0')}`,W/2,H/2-8);ctx.fillStyle='#ff4b4b';ctx.font='500 15px DM Mono';ctx.fillText(state.night===14?'THE HELICOPTER IS CLOSE.':'HOLD THE LINE.',W/2,H/2+26);}
  ctx.restore();requestAnimationFrame(draw);
}
function drawPlayer(){const p=state.player,a=Math.atan2(mouse.y-p.y,mouse.x-p.x);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.scale(ACTOR_SCALE,ACTOR_SCALE);ctx.fillStyle='#d2a371';ctx.fillRect(-10,-20,20,35);ctx.fillStyle='#29425b';ctx.fillRect(-12,10,24,18);ctx.fillStyle='#202834';ctx.fillRect(7,-6,35,8);ctx.fillStyle='#e7eef1';ctx.fillRect(36,-4,18,4);ctx.fillStyle='#d8b589';ctx.beginPath();ctx.arc(-2,-29,11,0,7);ctx.fill();ctx.restore();}
function drawBot(bot){ctx.save();ctx.translate(bot.x,bot.y);ctx.scale(ACTOR_SCALE,ACTOR_SCALE);ctx.fillStyle='#cda071';ctx.fillRect(-9,-19,18,33);ctx.fillStyle='#526f47';ctx.fillRect(-11,9,22,17);ctx.fillStyle='#26352b';ctx.fillRect(7,-6,31,7);ctx.fillStyle='#dce8d5';ctx.fillRect(34,-4,15,3);ctx.fillStyle='#d6ad87';ctx.beginPath();ctx.arc(-2,-28,10,0,7);ctx.fill();ctx.restore();ctx.fillStyle='#c8ff58';ctx.font='500 9px DM Mono';ctx.textAlign='center';ctx.fillText(`${Math.round(bot.accuracy*100)}% · ${bot.reload>0?'RELOAD':weapons[bot.weaponId].name}`,bot.x,bot.y+43);ctx.textAlign='left';}
function drawZombie(z){ctx.save();ctx.translate(z.x,z.y+Math.sin(performance.now()/220+z.bob)*2);ctx.fillStyle=z.color;ctx.beginPath();ctx.ellipse(0,8,z.r*.7,z.r,0,0,7);ctx.fill();ctx.fillStyle='#b9d893';ctx.beginPath();ctx.arc(0,-z.r*.65,z.r*.52,0,7);ctx.fill();if(z.armor){ctx.fillStyle='#4d5861';ctx.fillRect(-z.r*.6,-z.r*1.15,z.r*1.2,z.r*.4);}ctx.fillStyle='#241c1c';ctx.beginPath();ctx.arc(-z.r*.18,-z.r*.72,3,0,7);ctx.arc(z.r*.2,-z.r*.72,3,0,7);ctx.fill();if(z.clown){ctx.fillStyle='#ff3348';ctx.beginPath();ctx.arc(0,-z.r*.28,z.r*.16,0,7);ctx.fill();}if(z.boss){ctx.strokeStyle='#ffcf54';ctx.lineWidth=2;ctx.strokeRect(-z.r,-z.r*1.65,z.r*2,4);ctx.fillStyle='#ffcf54';ctx.fillRect(-z.r,-z.r*1.65,(z.hp/z.maxHp)*z.r*2,4);}ctx.restore();}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);requestAnimationFrame(loop);} 
function aimAt(event){const r=canvas.getBoundingClientRect();mouse.x=(event.clientX-r.left)*W/r.width;mouse.y=(event.clientY-r.top)*H/r.height;}
function beginFire(event){event.preventDefault();aimAt(event);mouse.down=true;if(state?.scene==='playing')shoot();}
canvas.addEventListener('pointermove',aimAt);canvas.addEventListener('pointerdown',event=>{beginFire(event);canvas.setPointerCapture?.(event.pointerId);});canvas.addEventListener('pointerup',event=>{mouse.down=false;canvas.releasePointerCapture?.(event.pointerId);});canvas.addEventListener('pointercancel',()=>mouse.down=false);
// Mouse fallback keeps desktop browsers and automation surfaces responsive; fire cooldown prevents duplicate pointer/mouse shots.
canvas.addEventListener('mousemove',aimAt);canvas.addEventListener('mousedown',beginFire);window.addEventListener('mouseup',()=>mouse.down=false);canvas.addEventListener('contextmenu',event=>event.preventDefault());window.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(state?.scene==='playing')pauseGame();else if(state?.scene==='paused')resumeGame();return;}keys.add(e.key.toLowerCase());if([' ','arrowup','arrowdown'].includes(e.key))e.preventDefault();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));document.querySelector('#soundButton').onclick=e=>{audio=!audio;e.target.textContent=`SOUND: ${audio?'ON':'OFF'}`;};
titleScreen();requestAnimationFrame(draw);requestAnimationFrame(loop);
